### ISSUE TITLE
Display issues on mobile devices

### ISSUE THREAD

**Issue by pbdevch** [SOBotics/Higgs#18]
I noticed some issues while displaying Higgs on my phone (Samsung Galaxy S7, running Android 7.0, with Chrome 64.0.3282.137). The first thing is the footer, which overflows the color of the `<div>` block it should be in:

![screenshot_20180305-103321](https://user-images.githubusercontent.com/7314572/36968493-f5897eae-2062-11e8-85c3-798ac44d9221.png)

On the 404 page, the xkcd image also overflows the page width and doesn't resize responsively:

![screenshot_20180305-091308](https://user-images.githubusercontent.com/7314572/36968571-2d9dcb88-2063-11e8-8326-cb9cb5e27842.png)

**Comment by rjrudman** [comment]
Yeah, I noticed this too. I'll take a look at it, but if anyone else is a bootstrap guru, I'd be happy for them to give it a crack

**Comment by rjrudman** [comment]
Also, the dropdown menu overflows the header

**Comment by paper1111** [comment]
Err this looks just weird...

![1f33f744-6b88-4a74-9222-a5b90e9cf502](https://user-images.githubusercontent.com/30367398/37140214-e91bbdc2-22eb-11e8-828c-0eba15d1335f.png)

**Comment by rjrudman** [comment]
@paper1111 Yeah, I was following a bootstrap4 tutorial for footers, but it appears to be completely broken when scrolling, and particularly for multi-line footers.

**Comment by pbdevch** [comment]
@rjrudman Is the Bootstrap 4 tutorial outdated? The first productive versoin was released on Jan 18th 2018.

**Comment by rjrudman** [comment]
@pbdevch BS4 should be the latest. I likely misunderstood how it worked and borked it somewhere

**Comment by pbdevch** [comment]
@rjrudman Ok. I just wanted to make that sure because I had some screwups with the Alpha versions back in 2016.

**Comment by pbdevch** [comment]
I've tested just a little bit with the CSS as the footer also appears to be borked on the Report site. I didn't look into the *actual* source code, but at least in Chrome's dev tools the issue can be fixed (in both mobile and desktop) by this CSS:

```css
.footer[_ngcontent-c0] {
    position: relative; /* Was "absolute before" */
    bottom: 0;
    width: 100%;
    /* height: 60px; * /* Removing/commenting out the height setting makes the background to go with the text, no matter how long it is */
    line-height: 60px;
    background-color: #f7f7f7;
}
```
@rjrudman Let me know if that helps, maybe I can throw in PR.
